data:
  in_memory: 1
  num_workers: 10
  in_memory: 1
  train_dataset: /checkpoint/caseymeehan/ffcv_datasets/100_per_class_A.beton
  val_dataset: /checkpoint/caseymeehan/ffcv_datasets/val.beton
  bboxA_dataset: /checkpoint/fbordes/ffcv_datasets_attack/100_per_class_bbox_A.beton
  bboxB_dataset: /checkpoint/fbordes/ffcv_datasets_attack/100_per_class_bbox_B.beton
  public_dataset: /checkpoint/fbordes/ffcv_datasets_attack/500_per_class_public.beton
attack:
  k: 20
  k_attk: 20
dist:
  world_size: 8
  nodes: 1
  use_submitit: 1
  use_volta32: 1
  partition: learnlab
logging:
  folder: /tmp/
lr:
  lr: 1.7
  lr_schedule_type: cyclic
model:
  arch: resnet101
  mlp: "2048-256"
simclr: 
  temperature: 0.15
resolution:
  end_ramp: 85
  max_res: 192
  min_res: 160
  start_ramp: 70
training:
  loss: "simclr"
  batch_size: 128
  bn_wd: 0
  distributed: 1
  epochs: 1000
  label_smoothing: 0
  momentum: 0.9
  optimizer: lars
  weight_decay: 1e-6
  base_lr: 0.3
  eval_freq: 100
validation:
  lr_tta: False
  resolution: 256
logging: 
  checkpoint_freq: 5
  snapshot_freq: 50
